bin: update grimshot with savecopy/wait/anything, fix color_picker flag order

diff --git a/bin/grimshot b/bin/grimshot
--- a/bin/grimshot
+++ b/bin/grimshot
@@ -13,14 +13,15 @@
 ## See `man 1 grimshot` or `grimshot usage` for further details.
 
 getTargetDirectory() {
-  test -f "${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs" && \
-    . "${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs"
+  test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" && \
+    . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
 
   echo "${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}"
 }
 
 NOTIFY=no
 CURSOR=
+WAIT=no
 
 while [ $# -gt 0 ]; do
   key="$1"
@@ -34,6 +35,15 @@ while [ $# -gt 0 ]; do
       CURSOR=yes
       shift # past argument
       ;;
+    -w|--wait)
+      shift
+      WAIT="$1"
+      if echo "$WAIT" | grep "[^0-9]" -q; then
+        echo "invalid value for wait '$WAIT'" >&2
+        exit 3
+      fi
+      shift
+      ;;
     *)    # unknown option
       break # done with parsing --flags
       ;;
@@ -44,15 +54,16 @@ ACTION=${1:-usage}
 SUBJECT=${2:-screen}
 FILE=${3:-$(getTargetDirectory)/$(date -Ins).png}
 
-if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "check" ]; then
+if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "savecopy" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimshot [--notify] [--cursor] (copy|save) [active|screen|output|area|window] [FILE|-]"
+  echo "  grimshot [--notify] [--cursor] [--wait N] (copy|save) [active|screen|output|area|window|anything] [FILE|-]"
   echo "  grimshot check"
   echo "  grimshot usage"
   echo ""
   echo "Commands:"
   echo "  copy: Copy the screenshot data into the clipboard."
   echo "  save: Save the screenshot to a regular file or '-' to pipe to STDOUT."
+  echo "  savecopy: Save the screenshot to a regular file and copy the data into the clipboard."
   echo "  check: Verify if required tools are installed and exit."
   echo "  usage: Show this message and exit."
   echo ""
@@ -62,6 +73,7 @@ if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "check" 
   echo "  output: Currently active output."
   echo "  area: Manually select a region."
   echo "  window: Manually select a window."
+  echo "  anything: Manually select an area, window, or output."
   exit
 fi
 
@@ -73,7 +85,12 @@ notifyOk() {
 
   TITLE=${2:-"Screenshot"}
   MESSAGE=${1:-"OK"}
-  notify "$TITLE" "$MESSAGE"
+
+  if [ "$ACTION" = "save" ] || [ "$ACTION" = "savecopy" ]; then
+    notify "$TITLE" "$MESSAGE" -i "$FILE"
+  else
+    notify "$TITLE" "$MESSAGE"
+  fi
 }
 notifyError() {
   if [ $NOTIFY = "yes" ]; then
@@ -143,23 +160,38 @@ elif [ "$SUBJECT" = "output" ] ; then
   OUTPUT=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')
   WHAT="$OUTPUT"
 elif [ "$SUBJECT" = "window" ] ; then
-  GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)
+  GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -r)
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
    exit 1
   fi
   WHAT="Window"
+elif [ "$SUBJECT" = "anything" ] ; then
+  GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -o)
+  # Check if user exited slurp without selecting the area
+  if [ -z "$GEOM" ]; then
+    exit
+  fi
+  WHAT="Selection"
 else
   die "Unknown subject to take a screen shot from" "$SUBJECT"
 fi
 
+if [ "$WAIT" != "no" ]; then
+  sleep "$WAIT"
+fi
+
 if [ "$ACTION" = "copy" ] ; then
   takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
-  notifyOk "$WHAT copied to buffer"
+  notifyOk "$WHAT copied to clipboard"
 else
   if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
     TITLE="Screenshot of $SUBJECT"
     MESSAGE=$(basename "$FILE")
+    if [ "$ACTION" = "savecopy" ]; then
+      wl-copy --type image/png < "$FILE" || die "Clipboard error"
+      MESSAGE="$MESSAGE and clipboard"
+    fi
     notifyOk "$MESSAGE" "$TITLE"
     echo "$FILE"
   else
